enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  ts-unused-exports@*:
    dependencies:
      typescript: ">=4.9.5"
  eslint-plugin-typescript-sort-keys@*:
    dependencies:
      typescript: ">=4.9.5"
